### ISSUE TITLE
Can you add auto Installation of LCD-show? Can we a sperate Image with that added for LCD screens

### ISSUE THREAD

**Issue by operationairstrike** [jayofelony/pwnagotchi-bookworm#12]

**Comment by jayofelony** [comment]
Nope sorry, I try to keep itas basic as I can. Not many users use 3.5 lcd. I try to steer clear of 3rd party software in my builds to limit the chances of breaks.

So no I will not release a separate image just for this.

**Comment by operationairstrike** [comment]
Ok
