### ISSUE TITLE
[BUG] When hitting Y to update, give strange response.

### ISSUE THREAD

**Issue by rsun0525** [jayofelony/pwnagotchi-bookworm#16]
**Describe the bug**

pi@pwnagotchi400:~ sudo pwnagotchi --check-update
There is a new version available! Update from v2.7.0 to v2.7.2?
[y(es)/n(o)]y
Okay, give me a couple minutes. Just watch pwnlog while you wait.
Okay, guess not!
You are currently on the latest release, v2.7.0.
pi@pwnagotchi400:~ $

**To Reproduce**

After hitting Y, get the extract statements that make no sense.

**Expected behavior**
Would expect only the first statement after hitting "y", the second statement for hitting no, and the third statement to show instead of asking whether I want to upgrade.

**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version 2.7.0
 - OS version
 - Type of hardware
 - Any additional hardware used

**Additional context**

**Comment by jayofelony** [comment]
Fixed in 2.7.1, boot to manual and it should update by auto-update.
