### ISSUE TITLE
[BUG]Restarting into manual mode instead of auto

### ISSUE THREAD

**Issue by Ravioli5** [jayofelony/pwnagotchi-bookworm#19]
When restarted, the pwnagotchi sometimes restarts in manual mode. Mildly annoying but can be changed back to auto mode. Happens every once in a while but not always.

1. Restart pwnagotchi
2. Check what mode it is in
3. I used web config restart to reproduce this bug, ssh didn't do the same thing yet

**Expected behavior**
Manual mode is coming instead of auto.

**Environment (please complete the following information):**
 - 2.7.3
 - bookworm
 - raspberry pi 4
 - ethernet cable to home network?

**Additional context**
This happened with the 2.6.9 and onwards too. I'm not sure about the previous ones as I have not tested

**Comment by jayofelony** [comment]
If you restarted into a certain mode from webui, you must refresh the webui after restarting in order to load the corresponding restart into "MANUAL/AUTO" button.

**Comment by Ravioli5** [comment]
I click the default refresh button and I do restart the webpage. I thought this was the problem too but I made sure to do it properly but it still happens.

 I usually wouldn't restart my pwnagotchi all the time however the wlanmon is having problems as it cannot collect handshakes after a while. It gets fixed after restarting for a while then I have to restart it again.

**Comment by Ravioli5** [comment]
Oh and when it shows manual mode the display is frozen so I cannot see if the pwnagotchi is working too. I use the web UI for now (display isn't going to be used for me)

**Comment by jayofelony** [comment]
In MANU display does not refresh.

**Comment by jayofelony** [comment]
You don't happen to have a usb cable connected to a pc as well?

**Comment by Ravioli5** [comment]
No but I do use the web UI with the pwnagotchi connected to a home router. I noticed that whenever i restart with web UI it restarts into manual mode. I'm not sure why cause I didn't click the restart into manual mode but it's happening more frequently now, more like nearly every time.

**Comment by Ravioli5** [comment]
It happens when the pwnagotchi is unplugged and then plugged in again too, but pwnkill has not done this yet.

**Comment by jayofelony** [comment]
I use a RPi4 and do not have this issue, and it is also connected by ethernet to my modem.

**Comment by Ravioli5** [comment]
Hmm I'm not sure then...

**Comment by Ravioli5** [comment]
What should I do? I don't want to reflash but I won't restart this many times if I didn't get the wlan0mon problem...

**Comment by Ravioli5** [comment]
Accidentally closed, sorry

**Comment by jayofelony** [comment]
Do you have another sd card on which you can flash 2.7.3 to test?

**Comment by Ravioli5** [comment]
I do. I'll try it and tell you what happens.

**Comment by Ravioli5** [comment]
I got a possible fix. The drivers may have crashed irreparablly and an outdated bootloader so I have to fix this

**Comment by Ravioli5** [comment]
Nope this did not fix it

**Comment by Ravioli5** [comment]
It's worse now, it allows you only to switch to manual mode from manual mode in the web UI, I'm going to attempt to fix it for a while

**Comment by jayofelony** [comment]
I don't know what is going on with your set-up, I cannot reproduce this in any way. Have you tried running without your custom config. Maybe there is a problem there?

**Comment by Ravioli5** [comment]
Ok I will try...

**Comment by Ravioli5** [comment]
Ok I'm having multiple web UI problems so I have to troubleshoot these for a while before I can get a actual report. I also have minor UI problems as well that didn't change with anything yet. I'll try to fix it on my own first before getting back

**Comment by Ravioli5** [comment]
I'm going to re image now as the pwnagotchi died after auto update

**Comment by Ravioli5** [comment]
Closed as cannot reproduce
