### ISSUE TITLE
Common white list

### ISSUE THREAD

**Issue by jagp8** [jayofelony/pwnagotchi-bookworm#24]
It would be great if we could define a single whitelist so we only have to modify it in one place instead of five.

I understand that having a whitelist for each plugin gives you more flexibility, but if you plan to put the same networks on all the whitelists, it's just a hindrance.

It would be great if we could have a common one that applies to all whitelists and have additional values for plugins whose flexibility we want to maintain.

**Comment by wpa-2** [comment]
Feel free to create a plugin I'm sure it would be welcome.

**Comment by jayofelony** [comment]
I think this is an easy change, I can just make the 3 plugins that currently use the whitelist setting look for the `main.whitelist` setting in config.

Current 3 plugins are wigle, wpa-sec and onlinehashcrack.

**Comment by jayofelony** [comment]
I forgot about grid, this also uses a whitelist. Called exclude, but I can change that.
