### ISSUE TITLE
[BUG] Terminal type doesn't seem to be working anymore?

### ISSUE THREAD

**Issue by rsun0525** [jayofelony/pwnagotchi-bookworm#25]
**Describe the bug**
When I use the arrow keys to try to navigate a text console screen, it just brings back the control characters.  For example, I'm installing pisugar-server through curl http://cdn.pisugar.com/release/pisugar-power-manager.sh | sudo bash, then when I use the arrow key to try to navigate the menu that comes up, the control keys come up.

![image](https://github.com/jayofelony/pwnagotchi-bookworm/assets/29848331/9601cf5c-a2a0-4cd6-af76-7e037eac3534)

When I did this on other versions of pwnagotchi, this procedure worked.

I'm just using putty to ssh into pwnagotchi.

This is from an initial install of 2.7.3

**Comment by wpa-2** [comment]
Install it this way and it works 
```
wget http://cdn.pisugar.com/release/pisugar-power-manager.sh
bash pisugar-power-manager.sh -c release
```
