### ISSUE TITLE
[BUG] Installed on Raspberry Pi Zero 2W and it's blind

### ISSUE THREAD

**Issue by rsun0525** [jayofelony/pwnagotchi-bookworm#26]
**Describe the bug**
Installed 2.7.3 on Raspberry Pi Zero 2W and it updated to 2.7.6, but still blind

At one point I had heard there's more than one WiFi chipset for Raspberry Pi Zero 2W, do you support both?

[pwnagotchi.log](https://github.com/jayofelony/pwnagotchi-bookworm/files/14016902/pwnagotchi.log)

**Comment by jayofelony** [comment]
Yes

**Comment by jagp8** [comment]
I have two Zeros2W and none of the is finding anithing since updated to 2.7.7 :S

**Comment by jagp8** [comment]
I did a sudo apt update and full-upgrade to force the update, maybe it's related

**Comment by jayofelony** [comment]
You shouldn't do that.. that might overwrite the custom wifi firmware. And probably did, as you say its blind now. Which has absolutely nothing to do with upgrading pwnagotchi.

You should run `sudo pwnagotchi --check-update`.

**Comment by rsun0525** [comment]
Redoing it again with the 2.7.3 (currently running 2.7.7) and not doing and sudo apt update and full-upgrade solved it.
