### ISSUE TITLE
Update command Issue

### ISSUE THREAD

**Issue by TeqTinkerer** [jayofelony/pwnagotchi-bookworm#27]
When using sudo apt-get update the device disconnects and is unable to update. The library is accessed but continuously disconnects.

**Comment by jayofelony** [comment]
Than don't do it, you might break stuff

**Comment by TeqTinkerer** [comment]
No sorry I think I couldn't explain it properly! This is an issue. After "sudo apt-get upgrade" command, the unit goes blind every time it is in AI/AUTO mode. Something is conflicting in the plugins complied in the config.toml. Thank you!

**Comment by jayofelony** [comment]
Yes because you may have overwritten the wifi firmware, don't do an upgrade unless specified.
