### ISSUE TITLE
[BUG] White list not working properly

### ISSUE THREAD

**Issue by jagp8** [jayofelony/pwnagotchi-bookworm#33]
**Describe the bug**
Despite having some networks in the whitelist, they continue to be pwned, generating a pcap file.

**To Reproduce**
I have 2 networks (let's call them default and custom) and 2 routers (one acting as a repeater). In my whitelist, I have 8 entries, covering all possibilities:

- default_network,
- router_mac,
- default network,
- repeater_mac,
- custom_network,
- router_mac,
- custom_network,
- repeater_mac,

However, pcap files still appear in the /root/handshakes folder with various combinations of them. As I write this, I have just been pwned and disconnected (because I enjoy hard rock and hard testing xD).

**Expected behavior**
Having all the combinations in the whitelist should ensure my safety.

**Environment (please complete the following information):**
- Pwnagotchi version: 2.7.7
- Type of hardware: Raspberry Pi Zero 2W
- Any additional hardware used: None

**Additional context**
Without knowledge of the code, I can only speculate that maybe I'm not forming the whitelists correctly. Perhaps the Pwnagotchi receives the default_network with the repeater_mac, and the first match it finds in the whitelist is the default_network with the router_mac. If one of the pairs doesn't match, it might stop checking the whitelist.

However, if I'm not mistaken, having only one of them in the whitelist should be sufficient for safety, right? I mean, including only the MAC addresses or the network IDs should be enough.

**Extra update**
I just added another network, let's call it neighbor_network with the corresponding neighbor_router_mac, and after a restart it keeps generatin the pcap file (I disabled deauth so I can't tell if it's deauthing or not, but I'll bet it would xD)

**Comment by jayofelony** [comment]
Yes, I am aware of this. I tried everything possible for not having it deauth/assoc whitelisted networks, but it is not being stopped 100%. On the other hand, 4 plugins use it to not report and that works! So no worries.
