### ISSUE TITLE
[BUG] text problem

### ISSUE THREAD

**Issue by Ravioli5** [jayofelony/pwnagotchi-bookworm#42]
**Describe the bug**
Strange text can appear in the place of the manual or ai. 

**To Reproduce**
1. Turn on pwnagotchi
2. open web ui
3. Wait for a few hours, repeat process several times to see this.

**Expected behavior**
???Strange text appeared

**Screenshots**

![pwnagotchi (6)~2](https://github.com/jayofelony/pwnagotchi-bookworm/assets/157115073/4c30cbb8-38c4-45d0-82af-483510266ac3)

**Environment (please complete the following information):**
 - Pwnagotchi version - latest, 2.8.0
 - OS version bookworm
 - Type of hardware rpi 4
 - Any additional hardware used ethernet cable, power source

**Additional context**
In the example it shows Tr01 but it has also shown other things and also has shown ai instead of AI. I know this isa very small bug and it's not even that annoying but I wondered why it was there.

**Comment by jayofelony** [comment]
You have a plugin called Miyagi enabled, good day.

**Comment by Ravioli5** [comment]
Ohhh... sorry for wasting your time then

**Comment by jayofelony** [comment]
All good, just happy to know there isnt anything wrong.. again hahaha

**Comment by Ravioli5** [comment]
😅
