### ISSUE TITLE
Single found AP list for wardriver plugin

### ISSUE THREAD

**Issue by JD-2006** [jayofelony/pwnagotchi-bookworm#55]
**Describe the solution you'd like**
Create a single 'found' list of AP's (MAC's) to eliminate duplicates across all future sessions. Just have
a CSV appended to. Wouldn't need sessions?

**Comment by jayofelony** [comment]
I have no wardriver plugin in the image

**Comment by JD-2006** [comment]
Doh! Got ahead of myself, and wrong branch. :(
