### ISSUE TITLE
[BUG] after update, reboots only in manual mode

### ISSUE THREAD

**Issue by Ravioli5** [jayofelony/pwnagotchi-bookworm#59]
Whenever the pwnagotchi is booted it boots into auto mode, and then says wifi recon flipped and then goes to manual mode, before it loads the ai. It then loads the ai IN MANUAL MODE! It just become a fusion of the two modes and I'm not sure what happened. The booting time is quite longer too. I'm not sure why this happened 

1. update pwnagotchi via auto update 
2. Open web ui
3. look at screen with eyes

**Expected behavior**
A strange thing happens on screen.

**Videos**

Manual mode problem
https://github.com/jayofelony/pwnagotchi-bookworm/assets/157115073/c6f6d704-3044-4f64-b7a3-6eeaa92060bd

Handshake problem(it's a long video it's not letting me upload, not sure where to upload it....)

**Environment (please complete the following information):**
 - 1.8.2 bookworm
 - Raspberry pi 4
 - ethernet cable?

**Additional context**
The pwnagotchi is unable to collect handshakes when this happens. Either this happens or the pwnagotchi just becomes unable to collect handshakes even though it was doing well before. Not sure why this is happening... I really hope this is a problem on my end but I've tried to fix it with no results. Plz help

**Comment by jayofelony** [comment]
You are powering it from pc to otg usb, power it from pc to other usb port. Or unplug it completely from pc/laptop and use a battery to power it.

**Comment by Ravioli5** [comment]
It's not plugged into a pc though... I'll try connecting it to a different outlet though.

**Comment by Ravioli5** [comment]
Ok I tried it with the same outlet and it started working again. The boot time is still long for some reason but the wifi recon flipped message still comes before the ai is loaded (hasn't happened before) and happens everytime instead of after a few hours or so and only rarely. Here's a video of it happening. 

https://github.com/jayofelony/pwnagotchi-bookworm/assets/157115073/ab62740a-6fd4-4a31-bdc2-797dc92c09a6

**Comment by jayofelony** [comment]
https://discord.gg/vrbMsCMJ

Please get on discord if you can. This is not a bug, you are the only one experiencing it. You must have done something out of the ordinary.

**Comment by Ravioli5** [comment]
Ok, I will check on discord

**Comment by Ravioli5** [comment]
I'll close for now
