### ISSUE TITLE
[BUG] how to install on OrangePi Zero 2W

### ISSUE THREAD

**Issue by Ddataa** [jayofelony/pwnagotchi-bookworm#69]
**Describe the bug**
I am trying to use this with a OrangePi Zero 2W.

after flashing on to sd-card and booting the device I dont know how to connect

**To Reproduce**
1. flash sd card
2. boot device

**Environment (please complete the following information):**
 - Pwnagotchi version latest
 - OS version latest
 - Type of hardware OrangePi Zero 2W
 - Any additional hardware used 2''7 Sharp Memory LCD

**Additional context**

**Comment by Ddataa** [comment]
considering I have a working bookworm on another sd-card for this device, is there a script to install from whithin ?

**Comment by Ddataa** [comment]
like if I clone the repo and start setup.py ?

**Comment by renewedbullet** [comment]
This is not for an orangepi zero 2w. An there is not a working image for a orange pi 2w they are barely supported by Armbian and likely won't get any Pwnagotchi release for a while if you are interested in other SBCs I recommend looking at Jayofelony repo for banana pi m4 zero.

**Comment by Ddataa** [comment]
Thanks

this one ?
https://github.com/jayofelony/bananagotchi

**Comment by Ddataa** [comment]
do you think I can run the setup.py directly ?

**Comment by Ddataa** [comment]
ok thanks!
