### ISSUE TITLE
Can I use it with a normal screen ?

### ISSUE THREAD

**Issue by operationairstrike** [jayofelony/pwnagotchi-bookworm#7]

**Comment by breaktonic** [comment]
Yep i think , it works as well with a touch screen
Ive added Driver for my Wifi antenna ( Alfa Awus 1900 )
![IMG_20240115_001456](https://github.com/jayofelony/pwnagotchi-bookworm/assets/61321358/5a45fe26-0390-41df-b0df-3a917ee81a70)
![IMG_20240115_001500](https://github.com/jayofelony/pwnagotchi-bookworm/assets/61321358/6fab14d3-7dc9-4c16-bf24-487ca4bf1bb8)

Thx a lot for this great project Jayofelony , you are my Hero :)

Ps : sorry for my bad english , im french xD

**Comment by jayofelony** [comment]
Pas de problème!! I'm probably as bad at French hahaha. But we understand each other.
