### ISSUE TITLE
How do I make it connect to my hotspot on my phone?

### ISSUE THREAD

**Issue by operationairstrike** [jayofelony/pwnagotchi-bookworm#8]
Because Bluetooth doesn't connect I tried manual connecting too but it won't connect to my phone automatically.

**Comment by operationairstrike** [comment]
Oh makes sense I forgot that how can I fix the Bluetooth problem?

**Comment by jayofelony** [comment]
https://pwnagotchi.ai/configuration/#bluetooth

The original docs still apply to my image.

**Comment by operationairstrike** [comment]
I read that already
